on:
  push:
  pull_request:
    branches:
      - master

name: build_deploy

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Install TinyTeX
        run: |
          install.packages('tinytex')
          tinytex::install_tinytex()
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          install.packages(c('remotes', 'BiocManager'))
          local_deps <- remotes::local_package_deps(dependencies = TRUE)
          deps <- remotes::dev_package_deps(dependencies = TRUE, repos = BiocManager::repositories())
          BiocManager::install(local_deps[local_deps %in% deps$package[deps$diff != 0]], Ncpu = 2L)
        shell: Rscript {0}

      - name: Session info
        run: |
          install.packages('sessioninfo')
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # - name: Render book (git)
      #   run: |
      #     bookdown::render_book('index.Rmd', 'bookdown::gitbook')
      #   shell: Rscript {0}

      # - name: Render book (pdf)
      #   run: |
      #     bookdown::render_book('index.Rmd', 'bookdown::pdf_book')
      #   shell: Rscript {0}

      # - name: Render book (epub)
      #   run: |
      #     bookdown::render_book('index.Rmd', 'bookdown::epub_book')
      #   shell: Rscript {0}
        
      - name: Render book (bs4_book)
        run: |
          bookdown::render_book('index.Rmd', 'bookdown::bs4_book')
        shell: Rscript {0}

      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          apt-get update && apt-get -y install rsync
          
      - name: Deploy ðŸš€
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _book
